### ISSUE TITLE
Log file is missing

### ISSUE THREAD

**Issue by vertisan** [inspircd/inspircd-docker#106]
Hi,  

In my `inspircd.conf` I have defined line for logs:
```
<log method="file" type="*" level="debug" target="logs/ircd.log">
```
but file is not generated, logs from docker are empty too.
Where is the problem? It's an original line where I changed only `type` to clear `*`.

**Comment by SadieCat** [comment]
If you're using v3 it should just be `target="ircd.log`.

**Comment by vertisan** [comment]
Changed and file is in `/inspircd/logs/ircd.log` and now it's works, thanks.

**Comment by vertisan** [comment]
Changed and file is in /inspircd/logs/ircd.log and now it works, thanks.

EDIT: I have reopened to ask - why the given path does not work? Does this mean that I can't indicate an alternative path for the log files?
What if I need more login tags?
@SadieCat

**Comment by SadieCat** [comment]
If the path doesn't exist then it will silently fail currently. This is scheduled to be fixed for v4 because the way the logging system works currently is very complex and i'm afraid to break stuff by changing it.

**Comment by vertisan** [comment]
I understand, thanks for your response.
