### ISSUE TITLE
Troubleshooting Linking 2 servers

### ISSUE THREAD

**Issue by jcoelh0** [inspircd/inspircd-docker#107]
I'm trying to figure out 

Running the command:
`docker exec *container-id* /conf/links.sh`
doesn't output anything..

The haproxy is working perfectly between the 2 servers but when I connect two clients (one to each server), they are in two separate servers instead of one linked between the two.
What am I doing wrong?

`
>  version: "3.7"
>  services:
>   
>   haproxy:
>     image: haproxy:alpine
>     volumes:
>       - ./haproxy/:/usr/local/etc/haproxy/
>     depends_on:
>       - inspircd1
>       - inspircd2
>     ports:
>       - "6667:6667"
>     networks:
>       - backend
> 
>   inspircd1:
>     image: inspircd/inspircd-docker
>     volumes:
>       - ./server1/conf/:/inspircd/conf/
>     environment:
>       INSP_NET_NAME: inspircd1
>       INSP_SERVER_NAME: inspircd1.local
>       INSP_NET_SUFFIX: .local
> 
>       INSP_LINK1_NAME: inspircd2.local
>       INSP_LINK1_IPADDR: inspircd2
>       INSP_LINK1_SENDPASS: password
>       INSP_LINK1_RECVPASS: password
>       INSP_LINK1_TLS_ON: "no"
>     ports:
>       - "6667" #client
>       - "7000" #server
>     networks:
>       - backend
>        # aliases:
>        #   - inspircd1.local
> 
>   inspircd2:
>     image: inspircd/inspircd-docker
>     volumes:
>       - ./server2/conf/:/inspircd/conf/
>     environment:
>       INSP_NET_NAME: inspircd2
>       INSP_SERVER_NAME: inspircd2.local
>       INSP_NET_SUFFIX: .local
>       
>       INSP_LINK2_NAME: inspircd1.local
>       INSP_LINK2_IPADDR: inspircd1
>       INSP_LINK2_SENDPASS: password
>       INSP_LINK2_RECVPASS: password
>       INSP_LINK2_TLS_ON: "no"
>     ports:
>       - "6667"
>       - "7000"
>     networks:
>       - backend
> 
> 
>  networks:
>   backend:
`

**Comment by SISheogorath** [comment]
You should run `/conf/link.sh LINK1` to see the resulting config.

**Comment by jcoelh0** [comment]
![image](https://user-images.githubusercontent.com/37152600/80367199-8ebb7f80-8882-11ea-8989-487009800299.png)

**Comment by jcoelh0** [comment]
Using docker compose it works perfect

**Comment by jcoelh0** [comment]
Using docker compose it works perfectly fine, but switching to docker swarm it can't connect..
