### ISSUE TITLE
Unable to load m_mysql.so

### ISSUE THREAD

**Issue by jcoelh0** [inspircd/inspircd-docker#108]
After loading all the modules, this error shows:
`Unable to load m_mysql.so: /inspircd/modules/m_mysql.so is not a module (no ABI symbol)`

I'm trying to connect a database to my inspIRCd servers and I'm not able.
I downloaded the dependencies and configured it in the dockerfile.
RUN ./configure --enable-extras m_mysql.cpp
RUN apk add --no-cache mariadb-dev

After the error, the image closes.

**Comment by SadieCat** [comment]
Apologies for the late response. This should be fixed in the latest build. Please reply if you're still having problems.
