### ISSUE TITLE
Cannot create oper/connect password.

### ISSUE THREAD

**Issue by scott1981** [inspircd/inspircd-docker#111]
when doing docker run -d --rm inspircd/inspircd-docker /mkpass hmac-sha256 password

will yield a different result each time the command is ran, 

adding the following as an environmental variable
INSP_OPER_PASSWORD_HASH=5c261b5ea08e0628d82e759ebeeb14d55b12cffb81d38505db8507deab38597f

does not help when doing /oper oper "password"

**Comment by SadieCat** [comment]
That doesn't look like an InspIRCd HMAC-SHA256 password.

You generate hashed passwords by loading the password_hash module and using /mkpasswd on the IRCd.

Any external tools for doing so are almost certainly not compatible with the password format used by InspIRCd.

**Comment by scott1981** [comment]
That worked! You have to connect to irc server and execute command from there!

How can I pass an hmac-sha256 hash as an env variable in docker-compose.yml file that contains a $ character?

Thanks

**Comment by SadieCat** [comment]
>How can I pass an hmac-sha256 hash as an env variable in docker-compose.yml file that contains a $ character?

Apologies for the late response. You would need to quote it. (i.e. `'foo$bar'`).
