### ISSUE TITLE
/mkpasswd - Unknown command: mkpasswd

### ISSUE THREAD

**Issue by nmartin867** [inspircd/inspircd-docker#112]
This might just be a question rather than an issue. Once I run this image in a container and connect to the server the following command is not recognized:

command: ` /mkpasswd hmac-sha256 somePass`
output: `Irssi: Unknown command: mkpasswd`

I see that the appropriate modules appear to be loaded correctly.

```
irc_1  | 
irc_1  | InspIRCd Process ID: 1
irc_1  | 
irc_1  | Loading core modules ....................
irc_1  | [*] Loading module:    m_md5.so
irc_1  | [*] Loading module:    m_sha256.so
```
Am I missing something? Thanks! Sweet Image.

**Comment by SadieCat** [comment]
You need to load the password_hash module.

**Comment by nmartin867** [comment]
Isn't it loaded by default? Is ` m_password_hash.so` not the correct module?


`irc_1  | [*] Loading module:    m_password_hash.so` <-- this is loaded.

**Comment by SadieCat** [comment]
Try `/quote mkpasswd` instead?

**Comment by SadieCat** [comment]
I'm going too assume this is solved.

If you have any more issues then please ask in irc.inspircd.org #inspircd. Thanks.
