### ISSUE TITLE
Links Do Nothing?

### ISSUE THREAD

**Issue by xnaas** [inspircd/inspircd-docker#115]
I've reviewed #101 and #107 but my links do absolutely nothing?

```
xnaas@xnaasSRV:~/docker/envs$ docker exec -it ircd /conf/links.sh LINK1
<link name="ircd1"
      ipaddr="ircd1"
      port="7000"
      sendpass="passwd"
      recvpass="passwd"
      allowmask="172.22.0.0/16"
      >
<autoconnect period="30" server="ircd1">
xnaas@xnaasSRV:~/docker/envs$ docker exec -it ircd1 /conf/links.sh LINK1
<link name="ircd"
      ipaddr="ircd"
      port="7000"
      sendpass="passwd"
      recvpass="passwd"
      allowmask="172.22.0.0/16"
      >
<autoconnect period="30" server="ircd">
```

Neither of these servers are talking to each other though...

What am I missing?

Edit: And yes, both of the docker containers are in the same docker network.

Edit 2: This is a fresh `:latest` pull, which is 3.7.0.

Edit 3: The servers can both ping each other...so something tells me something is wrong with the script or the script running. `links.conf` is always 0 bytes for both containers... 🤔

**Comment by SadieCat** [comment]
Hey, apologies for the late response.

Your autoconnect tags point to the servers they exist on. You should instead have one autoconnect on one server which connects to the other.

**Comment by xnaas** [comment]
I completely forgot about this issue and don't use inspircd anymore. Thank you, though.
