### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd-docker#116]
The rest of InspIRCd has migrated to GitHub Actions. Ideally the Docker container building stuff should too.

**Comment by SadieCat** [comment]
Working on this in my fork. @SISheogorath would it be possible for you to poke me on IRC or by email with the credentials for the user which is used to push updates?

**Comment by SISheogorath** [comment]
Done :)

**Comment by SadieCat** [comment]
Thanks.
