### ISSUE TITLE
HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by walkero-gr** [inspircd/inspircd-docker#118]
Hello there.
I try to set up my own irc server but I am getting all the time the following error on connection

> Irssi: Connection lost to irc.amiga.gr
> 18:00 -!- Irssi: Removed reconnection to server irc.amiga.gr port 6667
> 18:00 -!- Irssi: Looking up irc.amiga.gr
> 18:00 -!- Irssi: Reconnecting to irc.amiga.gr [95.217.15.210] port 6667 - use /RMRECONNS to abort
> 18:00 -!- Irssi: Connection to irc.amiga.gr established
> 18:00 -!- HTTP/1.1 400 Bad Request
> 18:00 -!- Content-Type: text/plain; charset=utf-8
> 18:00 -!- Connection: close
> 18:00 -!- Request
> 18:00 -!- Irssi: Connection lost to irc.amiga.gr

The log file gives me the following

```
Wed Jan 27 2021 17:51:31 core_dns: qdcount: 1 ancount: 1 nscount: 0 arcount: 0
Wed Jan 27 2021 17:51:31 core_dns: Unpack name 1.0.0.127.in-addr.arpa
Wed Jan 27 2021 17:51:31 core_dns: Unpack name 1.0.0.127.in-addr.arpa
Wed Jan 27 2021 17:51:31 core_dns: Unpack name localhost
Wed Jan 27 2021 17:51:31 core_dns: Invalid name
Wed Jan 27 2021 17:51:32 SOCKET: Accepting connection on socket [::]:6667 fd 10
Wed Jan 27 2021 17:51:32 USERS: New UUID for user: 69FAAAABK
Wed Jan 27 2021 17:51:32 USERS: New user fd: 10
Wed Jan 27 2021 17:51:32 SOCKET: New file descriptor: 10
Wed Jan 27 2021 17:51:32 core_dns: Processing request to lookup 127.0.0.1 of type 12 to 127.0.0.11
Wed Jan 27 2021 17:51:32 core_dns: Packing name 1.0.0.127.in-addr.arpa
Wed Jan 27 2021 17:51:32 core_dns: cache: Checking cache for 1.0.0.127.in-addr.arpa
Wed Jan 27 2021 17:51:32 SOCKET: Error on FD 10 - 'Connection closed'
Wed Jan 27 2021 17:51:32 USERS: QuitUser: 69FAAAABK=69FAAAABK 'Connection closed'
Wed Jan 27 2021 17:51:32 SOCKET: DoWrite on errored or closed socket
Wed Jan 27 2021 17:51:32 SOCKET: Remove file descriptor: 10
Wed Jan 27 2021 17:51:32 CULLLIST: Deleting @0x555560f8c3c0
```

I am not sure how to get more info on why this **HTTP/1.1 400 Bad Request** occurs and how exactly to proceed.
Can you please recommend what to check and how to proceed?
Also, I use traefik in front of the inspircd docker server.

**Comment by SadieCat** [comment]
Traefik appears to a HTTP reverse proxy. IRC does not operate over HTTP.

**Comment by walkero-gr** [comment]
What could I use that could manipulate the domains in front of the inspircd in case you want to have multiple docker servers, using different domains? Is there something that could do something like that?

**Comment by walkero-gr** [comment]
Also Traefik is able to do TCP routing (https://doc.traefik.io/traefik/routing/routers/#configuring-tcp-routers). This would work with the above case?

**Comment by SadieCat** [comment]
Probably? You'll need to look into how that works yourself though because I don't have a clue how it works.

**Comment by walkero-gr** [comment]
@SadieCat Don't worry. I will try to make it work. Thanks for your recommendations.
