### ISSUE TITLE
Consider migrating from Docker Hub to the GitHub Container Registry

### ISSUE THREAD

**Issue by SadieCat** [inspircd/inspircd-docker#134]
Unfortunately Docker have decided to suspend free teams access which will affect the InspIRCd container.

https://blog.alexellis.io/docker-is-deleting-open-source-images/

As we're already on GitHub a good alternative to this would be the GitHub Container Registry. The main downside to this would be that existing container users will need to manually migrate.

Thoughts? Alternatives? etc.

**Comment by Cronus89** [comment]
Plenty of projects did exactly this, i dont see any downsides, if someday GitHub does the same thing, you can just look again for somewhere else to go!

**Comment by Techman** [comment]
I support the move to GitHub. Docker seems content to shoot their feet.

**Comment by benharri** [comment]
don't use docker for inspircd but ghcr seems like a solid alternative

**Comment by SadieCat** [comment]
I've looked into the Docker-Sponsored Open Source Program and I'm unwilling to go through this because:

1. Despite claiming to be for "non-commercial projects" it seems to be designed by someone who thinks that open source projects have an associated company and/or industry. I have no idea how I'd even fill this in.
2. It apparently requires me to dox my anonymous GitHub Sponsors which I'm not willing to do (pretty sure this is against the GitHub TOS too).

I'm working on moving over to the GitHub Container Registry now. Will report back soon.

**Comment by SadieCat** [comment]
>On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan. 

Looks like Docker have changed their mind. I might look into publishing on both GHCR and Docker Hub to future proof things though.
