### ISSUE TITLE
Add config to set password in <connect main>

### ISSUE THREAD

**Issue by kjelle** [inspircd/inspircd-docker#74]
Hello.
It would be nice if one could set hash and password in the main <connect ..> block through config.

**Comment by kjelle** [comment]
I can add this to your repo, and send a PR

**Comment by SISheogorath** [comment]
Nice, I'll review your PR as soon as it lands :)

**Comment by kjelle** [comment]
@SISheogorath - very nice system you have here, starting travis builds on PR with new tests etc!
