### ISSUE TITLE
Module passforward is enabled by default

### ISSUE THREAD

**Issue by kjelle** [inspircd/inspircd-docker#76]
Hello.
Is there a reason for why passforward is enabled by default? I have network(s) without any services.. 
Could it be enabled by default, but configurable to disable it?

**Comment by kjelle** [comment]
I could also mention, that even if we have NICKSERV - and some people don't have or use registered nicks - they would get an error message on every connect.

**Comment by SISheogorath** [comment]
The configs are made up by @Adam- and are the same as we ship with the .deb and .rpm file for inspircd.

I agree that m_passforward isn't perfect for usage without nickserv/services in general. We can probably make it optional.
