### ISSUE TITLE
Update for 3.0

### ISSUE THREAD

**Issue by r734** [inspircd/inspircd-docker#84]
The current build only supports 2.x, but 3.0 was released recently and should be dockerized. I'm not very familiar with the intricacies of Inspircd and Docker, but I'll try to get at least a start on it and see if I can find some of the gotchas.

**Comment by SISheogorath** [comment]
There is already a version that worked for 3.0 during alpha. 

https://github.com/inspircd/inspircd-docker/tree/preview/3.0

Currently the entire config management is missing. So basically the upgrade of https://github.com/inspircd/inspircd-docker/tree/master/conf to version 3.

If someone wants to help here: https://docs.inspircd.org/3/configuration-changes/

But maybe a fresh rewrite would be better.

**Comment by r734** [comment]
I went with a fresh rewrite using [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds). My progress is [here](https://github.com/r734/inspircd-docker/tree/3.0).

Right now it just copies in the configs from the inspircd repo, but I'm working on updating and copying in the configs from this repo instead. I don't know if I'll get around to updating the .sh scripts in the conf folder.

I haven't done anything special with modules yet, so whatever is included in the build by default is included in the docker build, and nothing more.

Let me know if you're happy with this direction and I'll keep working on it.

**Comment by SISheogorath** [comment]
I looks good already, I guess the idea is to use this as minimal version and now add back old functionalities to get the same extensibility as the old version had (i.e. inject custom dependencies, build extras modules, add own modules, …).

Just the version part, I would recommend to use insp3 as default, because it allows us to build the latest version from the branch by default, we'll do the release versions using `.travis.yml`:

https://github.com/inspircd/inspircd-docker/blob/a61807e36879c1ce45fc321de44ff2da4e7928fb/.travis.yml#L8

This makes testing easier and provides more flexibility in the long run :)

**Comment by r734** [comment]
Okay, it now builds an image with a (very) minimal config file and a canned, self-signed cert.

- Clone the repo
- Build with `docker build -t inspircd3 .`
- Run with `docker run --rm -it -p 6667:6667 -p 6697:6697 -p 7000:7000 -p 7001:7001 inspircd3`
- Connect to localhost with an IRC client

I added `ssl_template.conf` to allow creating a self-signed cert with non-default values. It follows the format expected by the gnutls `certtool`. I need to make cert creation optional (and probably off by default...?).

I haven't done anything with modules (aside from gnutls) or config generation yet, which I plan to tackle next.

Let me know what you think. Is it ready for a PR to a new branch (3.0-dev maybe)?

**Comment by SISheogorath** [comment]
Yes, I'll open up a new branch to work on 3.0, but before we do that, we should fix the certificate generation.

Please check https://github.com/inspircd/inspircd-docker/blob/master/entrypoint.sh

There we create a certificate on startup, we won't run a certificate creation during build as this is a big no no. (As everyone would get the same cert when running the image).

I'll create a branch and you can go for it :)

In general good work! Looking forward to get this stuff merged :)

**Comment by r734** [comment]
#86 fixed this
