### ISSUE TITLE
inspircd 3 stuck exits due to incorrect paths

### ISSUE THREAD

**Issue by Magnus010** [inspircd/inspircd-docker#87]
Looks like the latest Docker Hub image has an inspiricd.conf file pointing to the wrong location for files:
`Could not read "/inspircd/conf/conf/docker.motd" for "motd" file at /inspircd/conf/inspircd.conf:180:71 (inside tag files at line 180)
`

`Could not read "/inspircd/conf/conf/modules.conf" for include at /inspircd/conf/inspircd.conf:551:34 (inside tag include at line 551)
`
I tried editing it line by line, but I just reverted to version 2.0.27 and that version is working now.

**Comment by SISheogorath** [comment]
@Magnus010 So you upgraded from version 2 to version 3?

Do you use docker.compose or a volume? In this case your configs are persistent and therefore you need to migrate them, following [the guide from the docs](https://docs.inspircd.org/3/configuration-changes/).

If you didn't do any modifications yourself and don't care about the generated certificates, just throw things away be removing the volume.

**Comment by Magnus010** [comment]
It's deployed via docker-compose, and it was set to take the latest tag. We do not have it volume mounted. We only noticed it was crashing yesterday, and it looks like it pulled down the image about 2 days ago?
I did a `docker rm -f ` and a `docker rmi -f` on the container and images to clean them out, then pulled them again. Still encountered the errors. Backed the version down to 2.0.27 and it worked again.

**Comment by SISheogorath** [comment]
docker-compose automatically create a volume for the defined volume at /conf/ for the 2.0 images and it seems like it continues to use them for the newer images.

You can run `docker-compose down -v` but careful, this will delete all volumes for your compose project. As alternative you should be able to stop and remove the inspircd container, remove the volume that is used with it and then start it as v3 container again.

**Comment by Magnus010** [comment]
Ah, that is good to know. I had no idea that docker-compose created it's own volumes.
Just ran that command, wiped out the ircd volumes, re-upped the compose file, and it's running fine!
Thanks for the help!
