### ISSUE TITLE
bootstrap.sh exposing same port twice

### ISSUE THREAD

**Issue by meo-tech** [inspircd/inspircd-docker#98]
# Check for available ports
if [ "$(netstat -ln | grep -c :6667)" -eq 0 ]; then
   RUNPARAM="$RUNPARAM -p 6667:6667"
else
   RUNPARAM="$RUNPARAM -p 6667"
   echo "exposing 6667 on random port. Check \'docker ps\' for details"
fi

if [ "$(netstat -ln | grep -c :6697)" -eq 0 ]; then
   RUNPARAM="$RUNPARAM -p 6697:6697"
else
   RUNPARAM="$RUNPARAM -p 6697"
   echo "exposing 6697 on random port. Check \'docker ps\' for details"
fi

**Comment by SISheogorath** [comment]
Am I misreading or you? I see 66**9**7 and 66**6**7, what do you see?

**Comment by meo-tech** [comment]
Sorry, my fault. Must clean my glasses...

Sheogorath <notifications@github.com> schrieb am Do., 19. Sep. 2019, 22:31:
