### ISSUE TITLE
Healthcheck interval makes for a lot of noise

### ISSUE THREAD

**Issue by alandrees** [inspircd/inspircd-docker#99]
After firing up the docker image, I noticed there is a lot of noise related to doing dns resolution on 127.0.0.1.

I figured out it was due to the health check , running every 1 second.

Might be worthwhile to either a) give it a configurable interval or b) have facilities to quell the noise for the health-check specifically.

**Comment by SISheogorath** [comment]
Oh, agreed, 1 seconds is a bit much, I didn't see that part:

https://github.com/inspircd/inspircd-docker/blob/bfbc233cae332cd84e54afbe8cb860411773f6f6/Dockerfile#L58

I guess once a minute would be fine as well. Can you provide the error message you see? Maybe I can motivate @SaberUK to add an option to ignore 127.0.0.1 (or other network masks) for those :)

**Comment by alandrees** [comment]
I had to build the image without the healthcheck to keep my server up this morning, so I'll have to pull up a dev version.

**Comment by alandrees** [comment]
Going to open another issue regarding the health-check crashing issue.

**Comment by alandrees** [comment]
@SISheogorath This is the message that keeps repeating:

`Mon Sep 30 2019 23:26:00 core_dns: cache: Checking cache for 1.0.0.127.in-addr.arpa`
